apiVersion: 1
deleteDatasources:
  - name: prometheus
    orgId: 1
datasources:
- name: prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: https://prometheus.jed.local
  basicAuth: false
  editable: true
  tlsSkipVerify: true