apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases

components:
- ../../components/webhook
- ../../prometheus-system

patches:
- path: patch-webhooks.yaml
  target:
    group: admissionregistration.k8s.io
    
namespace: prometheus
