apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-operator
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - serviceaccounts
  - configmaps
  - services
  - namespaces
  - nodes/proxy
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - collectors
  - fluentbits
  - clusterfluentbitconfigs
  - clusterfilters
  - clusterinputs
  - clusteroutputs
  - clusterparsers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentd.fluent.io
  resources:
  - fluentds
  - fluentds/status
  - clusterfluentdconfigs
  - clusterfluentdconfigs/status
  - fluentdconfigs
  - fluentdconfigs/status
  - clusterfilters
  - filters
  - clusteroutputs
  - outputs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create

