apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  namespace: logging
spec:
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent
  tolerations:
  - effect: NoSchedule
    operator: Exists
  positionDB:
    hostPath:
      path: /var/lib/fluent-bit
  rbacRules:
    - apiGroups: [""]
      resources: ["nodes/proxy"]
      verbs: ["get"]
  dnsPolicy: ClusterFirstWithHostNet

---

apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFluentBitConfig
metadata:
  name: fluent-bit-config
spec:
  service:
    logLevel: info
    parsersFile: parsers.conf