apiVersion: fluentd.fluent.io/v1alpha1
kind: Fluentd
metadata:
  name: fluentd
  namespace: fluent
  labels:
    app.kubernetes.io/name: fluentd
spec:
  tolerations:
  - effect: NoSchedule
    operator: Exists
  replicas: 3
  buffer:
    DisableBufferVolume: false
    emptyDir: {}