apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: kube-system

images:
- name: docker.io/bitnami/sealed-secrets-controller
  newTag: v0.19.3

patchesStrategicMerge:
  - patch-deployment.yaml
