apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  template:
    tolerations:
    - key: "type"
      operator: Equal
      value: manager
      effect: NoSchedule
