apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
- ../../base
- ingress.yaml

patches:
- path: patch-statefulset.yaml

images:
- name: grafana/grafana
  newTag: 9.3.6

