apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
- ../../base
- ingress.yaml

patches:
- path: patch-statefulset.yaml

images:
- name: grafana/grafana
  newTag: 9.3.6

configMapGenerator:
  - name: grafana-config
    namespace: grafana
    files:
    - config/grafana.ini

  - name: provider-cilium
    namespace: grafana
    files:
    - config/provider-cilium.yaml
  
  - name: datasource-prometheus
    namespace: grafana
    files:
    - config/datasource-prometheus.yaml
  
  - name: grafana-cilium-dashboard
    namespace: grafana
    files:
    - dashboards/cilium-dashboard.json
  
  - name: grafana-hubble-dashboard
    namespace: grafana
    files:
    - dashboards/hubble-dashboard.json
    