apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  template:
    spec:
      containers:
        - name: grafana
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
            - mountPath: /etc/grafana
              name: grafana-config
      volumes:
      - name: grafana-config
        configMap:
          defaultMode: 420
          name: grafana-config
  volumeClaimTemplates:
  - metadata:
      name: grafana-pv
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: "longhorn-xfs"
      resources:
        requests:
          storage: 10Gi
