apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
components:
- ../../components/high-availability-1.21+
- ../../components/release

namespace: kube-system

images:
- name: gcr.io/k8s-staging-metrics-server/metrics-server
  newTag: master