apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
- ../../components/prometheus-metrics


replicas:
- name: cert-manager-webhook
  count: 2
- name: cert-manager
  count: 2
- name: cert-manager-cainjector
  count: 1

