apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- jenkins-ingress.yaml
- secret-jenkins-ingress.yaml

namespace: jenkins

images:
- name: jenkins/jenkins
  newTag: lts-jdk11

patchesStrategicMerge:
- patch-deployment.yaml
