apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../bases/
- traefik-dashboard-ingressroute-https.yaml
- secret-traefik-ingress.yaml
- secret-traefik-cacerts.yaml
- secret-default-tls.yaml
- tlsstore.yaml

namespace: traefik

images:
- name: traefik
  newTag: v2.9
  newName: traefik

patchesStrategicMerge:
  - patch-daemonset.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: traefik-config
  namespace: traefik
  files:
  - traefik-config.yaml

