kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik-ingress
  namespace: traefik
spec:
  template:
    spec:
      nodeSelector:
        app.kubernetes.io/name: traefik
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
        - name: traefik
          ports:
            - name: web
              containerPort: 80
              hostPort: 8550
            - name: dashboard
              containerPort: 8080
            - name: websecure
              containerPort: 443
              hostPort: 8551
