apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default
spec:
  certificates:
#    - secretName: default-ingress-tls
    - secretName: test-ingress-tls
  defaultCertificate:
    secretName: test-ingress-tls