providers:
  kubernetesCRD:
    namespaces: {}
    ingressClass: "traefik"
    allowEmptyServices: true
    throttleDuration: 10s
  kubernetesIngress:
    namespaces: {}
    ingressClass: "traefik"
    allowEmptyServices: true
    throttleDuration: 10s
api:
  dashboard: true
  insecure: false
ping:
  entryPoint: ping
log:
  level: info
  filePath: /dev/stdout
  format: json
accessLog:
  filePath: /dev/stdout
  format: json
serversTransport:
  rootCAs:
  - traefik-cacerts
entryPoints:
  web:
    address: ":80"
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    address: ":443"
  ping:
    address: ":8081"