providers:
  kubernetesCRD:
    namespaces: {}
    ingressClass: "traefik"
    allowEmptyServices: true
    throttleDuration: 10s
  kubernetesIngress:
    namespaces: {}
    ingressClass: "traefik"
    allowEmptyServices: true
    throttleDuration: 10s
api:
  dashboard: true
  insecure: false
ping:
  entryPoint: ping
log:
  level: info
  filePath: /dev/stdout
  format: json
accessLog:
  filePath: /dev/stdout
  format: json
serversTransport:
  rootCAs:
  - /var/traefik/certs/jed-ca.crt
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  ping:
    address: ":8081"